<a href="https://colab.research.google.com/github/ShruthiRamesh02/Python/blob/main/Python_Numpy_Code_Shruthi_T_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1
Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [1]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Set even-indexed rows and columns to 1
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Question 2
Create a 2d array of 8*8 matrix with 1 on the border and 0 inside

In [1]:
import numpy as np

# Create an 8x8 matrix filled with ones
matrix = np.ones((8, 8), dtype=int)

# Set the inner elements to 0
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


Question 3
Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np

# Create an array with values ranging from 0 to 8
arr = np.arange(9)

# Reshape the array to a 3x3 matrix
matrix = arr.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Question 4
Create a vector with values ranging from 10 to 49 and then reverse the vector.

In [3]:
import numpy as np

# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Question 5
Find indices of non-zero elements from the numpy array - [1,2,0,0,4,0]

In [4]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

# Find the indices of non-zero elements
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


Question 6
Wrire a recursive function that generates Fibonacci sequence of n numbers. For example, first 10 (n = 10) numbers in the sequence are 0, 1, 1, 2, 3, 5, 8, 13, 21, 34

In [5]:
def fibonacci_recursive(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_list = fibonacci_recursive(n - 1)
        fib_list.append(fib_list[-1] + fib_list[-2])
        return fib_list

# Example usage for the first 10 Fibonacci numbers
n = 10
fib_sequence = fibonacci_recursive(n)
print(' '.join(map(str, fib_sequence)))

0 1 1 2 3 5 8 13 21 34


Question 7
Check whether a number is even or odd using lambda function

In [6]:
number = 5

check_even_odd = lambda x: "Even number" if x % 2 == 0 else "Odd number"
result = check_even_odd(number)

print(result)  # Output: Odd number

Odd number
